name: Ruby

on:
  push:
  pull_request:

env:
  JIRA_SITE_URL: "http://cbroult.atlassian.net:443/"
  JIRA_USERNAME: "cbroult@yahoo.com"
  JIRA_API_TOKEN: "${{secrets.JIRA_API_TOKEN}}"
  JIRA_BOARD_NAME:  "JATCIGALX - Supply"
  JIRA_BOARD_NAME_REGEX: "JATCIGALX"
  SPRINT_FIELD_NAME: "Sprint"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4.1'

    env:
      REDIS_PORT: 6379

    services:
      redis:
        image: redis:alpine
        ports:
          - ${{ env.REDIS_PORT }}:${{ env.REDIS_PORT }}
#        options: >-
#          --requirepass secret_password

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test Redis Connection
      run: redis-cli -p ${{ env.REDIS_PORT }} ping

    - name: Run the default task
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ env.REDIS_PORT }}
      run: bundle exec rake
