name: Ruby

on:
  push:
  pull_request:

env:
  JIRA_SITE_URL: "http://cbroult.atlassian.net:443/"
  JIRA_USERNAME: "cbroult@yahoo.com"
  JIRA_API_TOKEN: "${{secrets.JIRA_API_TOKEN}}"
  JIRA_BOARD_NAME:  "JATCIGALX - Supply"
  JIRA_BOARD_NAME_REGEX: "JATCIGALX"
  SPRINT_FIELD_NAME: "Sprint"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4.1'

    services:
      redis:
        image: redis:alpine

    steps:
    - uses: actions/checkout@v4

    - name: Install Redis CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test Redis Connection
      run: redis-cli ping

    - name: Run the default task
      run: bundle exec rake
