name: Ruby

on:
  push:
  pull_request:

env:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  LC_CTYPE: en_US.UTF-8
  DISABLE_COVERAGE: "true"
  JIRA_SITE_URL: "http://cbroult.atlassian.net:443/"
  JIRA_USERNAME: "cbroult@yahoo.com"
  JIRA_PROJECT_KEY: "JATCIGHALX"
  JIRA_API_TOKEN: "${{secrets.JIRA_API_TOKEN}}"
  JIRA_SPRINT_FIELD_NAME: "Sprint"
  REDIS_PORT: 6379

jobs:
  build:
    name: Ruby ${{ matrix.os }} ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #, windows-latest ]
        ruby: ['3.4.1', '3.4.2']
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"

    steps:
    - uses: actions/checkout@v4

    - name: Dynamically set additional variables
      run: |
        export JAT_TICKETS_FOR_TEAM_SPRINT_TICKET_DISPATCHER_JQL="project = ${{env.JIRA_PROJECT_KEY}} AND ${{env.JIRA_SPRINT_FIELD_NAME}} IS EMPTY"
        echo "JAT_TICKETS_FOR_TEAM_SPRINT_TICKET_DISPATCHER_JQL=$JAT_TICKETS_FOR_TEAM_SPRINT_TICKET_DISPATCHER_JQL" >> $GITHUB_ENV
        export JIRA_BOARD_NAME="${{env.JIRA_PROJECT_KEY}} - Delivery"
        echo "JIRA_BOARD_NAME=$JIRA_BOARD_NAME" >> $GITHUB_ENV
        export JIRA_BOARD_NAME_REGEX="${{env.JIRA_PROJECT_KEY}}"
        echo "JIRA_BOARD_NAME_REGEX=$JIRA_BOARD_NAME_REGEX" >> $GITHUB_ENV

    - name: Install Redis CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools

    - name: Wait for Redis
      run: |
        for i in {1..10}; do
          (echo > /dev/tcp/localhost/$REDIS_PORT) >/dev/null 2>&1 && break
          echo "Waiting for Redis to start $i..."
          sleep 4
        done
        echo "Redis is ready to accept connections on port $REDIS_PORT"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test Redis Connection
      run: redis-cli -p $REDIS_PORT ping

    - name: Run the default task
      run: bundle exec rake
